### PR TITLE
TVM Upgrade 2023.07

### LINKED ISSUE #4: Add new opcodes introduced in TVM Upgrade 2023.07
See: https://docs.ton.org/learn/tvm-instructions/tvm-upgrade-2023-07

### PR DESCRIPTION
**Pull request by Gusarich**
closes #4

### CODE REVIEW

**Comment by 0kenx** [comment]
@anton-trunov Can this be merged? I'm looking to use it in a project.

**Comment by 0kenx** [comment]
When trying to get this to work I ran into another possible issue, the [emulator](https://github.com/tact-lang/tact-emulator/tree/main/src/bindings/wasm) doesn't seem to support new opcodes.

Do you know from which source is this emulator wasm compiled?

**Comment by 0kenx** [comment]
to answer my own question: https://github.com/tact-lang/tact-emulator/pull/12

**Review by novusnota — APPROVED** [review]
LGTM!

**Comment by Gusarich** [comment]
@anton-trunov done

**Review by anton-trunov — APPROVED** [review]

**Pull request merged**
